function BlackRow() {
    return (
        <div class="container">
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
            <div class="white"></div>
            <div class="black"></div>
        </div>
    );
}

export default BlackRow